# Standards: 1.5
---
- name: list all containers
  command: "docker ps -a --filter status=exited --format '{{ '{{' }} .Names {{ '}}' }}'"
  register: containers
  changed_when: false

- name: remove non-kubernetes containers
  docker_container:
    name: "{{ item }}"
    state: absent
  with_items: "{{ containers.stdout_lines|default([]) }}"
  when: item.find('k8s') == -1
